name: C/C++ CI Windows Server 2019 x64 pow-miner+pow-miner-cuda+lite-client Compile

on:
  push:
    tags:
    - '*'

defaults:
  run:
    shell: cmd
    
jobs:
  build:

    runs-on: windows-2019

    steps:
      - name: Get Current OS version
        run: |
          systeminfo | findstr /B /C:"OS Name" /C:"OS Version"

      - name: Check out current repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          
      - name: Check out zlib repository
        uses: actions/checkout@v2
        with:
          repository: desktop-app/zlib
          path: zlib
          
      - name: Check out vcpkg repository
        uses: actions/checkout@v2
        with: 
            repository: microsoft/vcpkg
            path: vcpkg     
          
      - name: Setup msbuild.exe
        uses: microsoft/setup-msbuild@v1.0.3

      - uses: Jimver/cuda-toolkit@v0.2.4
        id: cuda-toolkit
        with:
            cuda: '11.4.0'

      - name: Show nvidia cuda toolkit version 
        run: |
          nvcc -V  
      
      - name: Compile zlib Win64
        run: |
          cd zlib\contrib\vstudio\vc14          
          msbuild zlibstat.vcxproj /p:Configuration=Debug /p:platform=x64        
          msbuild zlibstat.vcxproj /p:Configuration=ReleaseWithoutAsm /p:platform=x64

      - name: Configure vcpkg
        run: |
          cd vcpkg
          bootstrap-vcpkg.bat        
          vcpkg integrate install
          
      - name: Install vcpkg openssl
        run: |
          cd vcpkg     
          vcpkg install openssl:x64-windows
             
      - name: Generate cmake files
        run: |
          set root=%cd%
          echo %root%
          mkdir build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=%root%/vcpkg/scripts/buildsystems/vcpkg.cmake -DMINERCUDA=true -DZLIB_FOUND=1 -DZLIB_INCLUDE_DIR=%root%\zlib -DZLIB_LIBRARY=%root%\zlib\contrib\vstudio\vc14\x64\ZlibStatReleaseWithoutAsm\zlibstat.lib -DCMAKE_CXX_FLAGS="/DTD_WINDOWS=1 /EHsc /bigobj /W0" -DCMAKE_BUILD_TYPE=Release ..
          
      - name: Compile pow-miner
        run: |       
          cd build
          cmake --build . --target pow-miner --config Release
        continue-on-error: true          
        
      - name: Compile pow-miner-cuda
        run: |       
          cd build
          cmake --build . --target pow-miner-cuda --config Release
        continue-on-error: true
        
      - name: Compile lite-client
        run: |       
          cd build
          cmake --build . --target lite-client --config Release
        continue-on-error: true
          
      - name: Show executables
        run: |
          cd build
          dir pow-miner*.exe /a-D /S /B
          dir lite-client.exe /a-D /S /B
           
      - name: Find & copy binaries with dependencies
        run: |
          mkdir artifacts
          for /d /r %%a in (*) do @if exist %%a\pow-miner.exe (copy /Y %%a\* artifacts\ )
          for /d /r %%a in (*) do @if exist %%a\pow-miner-cuda.exe (copy /Y %%a\* artifacts\ )
          for /d /r %%a in (*) do @if exist %%a\lite-client.exe (copy /Y %%a\* artifacts\ )
          
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: win64-pm-pmocl-lc-binaries
          path: artifacts
